baseURL: "https://blog.tneitzel.eu/"
title: qtc's blog
paginate: 5
theme: PaperMod
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about
      name: about
      url: /
      weight: 10
    - identifier: posts
      name: posts
      url: /posts/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 30
    - identifier: tags
      name: tags
      url: /tags/
      weight: 40
    - identifier: categories
      name: categories
      url: /categories/
      weight: 50
    - identifier: search
      name: search
      url: /search/
      weight: 60

params:
  env: production
  title: qtc's blog
  description: "InfoSec Articles"
  keywords: [InfoSec, Hacking, Programming, Pentest]
  author: Tobias Neitzel
  DateFormat: "January 2, 2006"
  defaultTheme: auto

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  SocialIconsFooter: true

  assets:
    disableHLJS: true
    favicon: "/img/favicon.ico"
    favicon16x16: "/img/favicon.ico"
    favicon32x32: "/img/favicon.ico"
    apple_touch_icon: "/img/favicon.ico"
    safari_pinned_tab: "/img/favicon.ico"

  label:
    text: "qtc's blog"
    icon: "/img/profile.png"
    iconHeight: 35

  profileMode:
    enabled: true
    title: qtc's blog
    subtitle: |-
      Hi there! I'm Tobias, pentester and security researcher at [usd AG](https://www.usd.de/)
      and this is my personal blog. The articles contained in this blog discuss different infosec
      related topics. Writing blog posts is a great way to learn and I hope you also enjoy reading
      them ;)
    imageUrl: "/img/profile.png"
    imageWidth: 200
    imageHeight: 200
    imageTitle: profile

  socialIcons:
    - name: twitter
      url: "https://twitter.com/qtc_de"
    - name: github
      url: "https://github.com/qtc-de"
    - name: linkedin
      url: "https://www.linkedin.com/in/tobias-neitzel-9b5998219"
    - name: RSS
      url: "/posts/index.xml"

  editPost:
    URL: "https://github.com/qtc-de/blog/tree/main/content/"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
    highlight:
        codeFences: true
        guessSyntax: true
        style: friendly
        noClasses: true
